Repository yesodweb/persistent, pull requests merged in 2020-03, with the labels that each got.

#1006 added explicit forall notation to make TypeApplications easier to use
  persistent/ChangeLog.md
  persistent/Database/Persist/Class/DeleteCascade.hs
  persistent/Database/Persist/Class/PersistQuery.hs
  persistent/Database/Persist/Class/PersistStore.hs
  persistent/Database/Persist/Class/PersistUnique.hs
  persistent/Database/Persist/Sql/Orphan/PersistStore.hs
  persistent/Database/Persist/Sql/Orphan/PersistUnique.hs
  persistent/Database/Persist/Sql/Run.hs
Labels: breaking

#1036 JSON instances require an extraneous id field for entities with a Primary
  persistent-template/Database/Persist/TH.hs
  persistent-test/src/PersistentTest.hs
  persistent-test/src/PersistentTestModels.hs
  persistent/ChangeLog.md
  persistent/Database/Persist/Class/PersistEntity.hs
Labels: work in progress

#996 Handle foreign key constraint names over 63 characters for Postgres
  persistent-mysql/ChangeLog.md
  persistent-mysql/Database/Persist/MySQL.hs
  persistent-mysql/README.md
  persistent-mysql/persistent-mysql.cabal
  persistent-mysql/test/main.hs
  persistent-postgresql/ChangeLog.md
  persistent-postgresql/Database/Persist/Postgresql.hs
  persistent-postgresql/test/main.hs
  persistent-sqlite/ChangeLog.md
  persistent-sqlite/Database/Persist/Sqlite.hs
  persistent-sqlite/test/main.hs
  persistent-test/persistent-test.cabal
  persistent-test/src/LongIdentifierTest.hs
  persistent/ChangeLog.md
  persistent/Database/Persist/Sql/Internal.hs
Labels: breaking, enhancement
